#!/usr/bin/env sh


#RODA PHPSTAN
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPStan. Arrume antes de continuar..."
    exit 1
fi


#RODA OS TESTES 
php artisan test --parallel
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar..."
    exit 1
fi
#RODA PINT
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.php$" || true)

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "$FILE"
    git add "$FILE"
done