#!/usr/bin/env sh

./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPStan. Arrume antes de continuar..."
    exit 1
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.php$" || true)

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "$FILE"
    git add "$FILE"
done